import Head from "next/head";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";
import StateContext, { ContextProvider } from "@/contexts/ContextProvider";
import { useContext } from "react";
import Navbar from "@/components/Navbar";
import Body from "@/components/Body";
import { MdOutlineMessage } from "react-icons/md";
import Link from "next/link";

export default function Home() {
  const { activeMenu } = useContext<any>(StateContext);
  return (
    <ContextProvider>
      <Head>
        <title>Frontend Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative">
          <Navbar />
          <div className="flex">
            <Sidebar />
            <Body />
          </div>
          <Link href="/chat">
            <div className="flex justify-center items-center rounded-full w-16 h-16 bg-[#326BFF] bottom-10 right-4 fixed">
              <MdOutlineMessage className="text-3xl text-white" />
            </div>
          </Link>
        </div>
      </main>
    </ContextProvider>
  );
}
